apiVersion: v1
kind: Service
metadata:
  labels:
    app: google-auth
  name: google-auth
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: google-auth
  type: NodePort
